### ISSUE TITLE
Laravel / VueJS

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [sebastienheyd/laravel-systempay#3]
Hello,

Would it be possible to use this package with Laravel & VueJS ?

Regards,
David

**Comment by sebastienheyd** [comment]
Hello,

I'm not a VueJS expert but it will be certainly possible by using an ajax call. 

To do that, you need to create a controller that will render only the button by passing it the amount and the transaction id.

Catch the ajax response data to assign it to a VueJS data variable or prop to show the button.

I hope I've answered the question?

**Comment by ShapesGraphicStudio** [comment]
Hi,

Yes, thanks a lot for that answer and the work shared with this package !

Regards
